Repository shescoding/shescoding-dot-org, pull requests merged in 2018-10, with the labels that each got.

#130 Changed Miki's title
  app/views/static_pages/team.html.erb
Labels: hacktoberfest, website

#132 Issue #120 - Add Brenda Stensland to /team
  app/assets/images/team/brenda.jpeg
  app/views/static_pages/team.html.erb
Labels: hacktoberfest, website

#134 jshint support
  Gemfile
  config/jshint.yml
Labels: hacktoberfest, infrastructure

#149 added Aeone Singson to team page issue #139
  app/assets/images/team/aeone.jpeg
  app/views/static_pages/team.html.erb
Labels: HTML / CSS / Javascript, content update, hacktoberfest

#138 Added drop down button for resources categories issue #53
  app/assets/stylesheets/resources.css.scss
  app/views/resources/index.html.erb
Labels: HTML / CSS / Javascript, enhancement, hacktoberfest, mobile

#154 Add docs on running JSHint
  README.md
Labels: content update, hacktoberfest

#155 Fix typo in README
  README.md
Labels: content update
